config/routes.rb
Rails.application.routes.draw do
  # get '/pets', to: 'pets#index', as: :pets
  # get '/pets/new', to: 'pets#new', as: :new_pet
  # get '/pets/:id', to: 'pets#show', as: :pet
  # post '/pets', to: 'pets#create'
  # get '/pets/:id/edit', to: 'pets#edit', as: :edit_pet
  # patch '/pets/:id', to: 'pets#update'
  # delete '/pets/:id', to: 'pets#destroy', as: :delete_pet

  resources :pets
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = %w(dog cat bird mouse spider rabbit snake)
  validates :name, :address, presence: true
  validates :species, inclusion: { in: SPECIES }

  def found_days_ago
    "#{(Date.today - found_on).to_i} days ago."
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render 'new'
    end
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    @pet.update(pet_params)
    redirect_to pet_path(@pet)
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
    redirect_to pets_path
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :address, :species, :found_on)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets593</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container mt-3">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pets/_form.html.erb
<%= simple_form_for @pet do |f| %>

  <%= f.input :name %>

  <%= f.input :address %>
  <div class="my-3">
    <%= f.date_field :found_on %>
    <%= f.select :species, collection: Pet::SPECIES %>
    <%= f.submit class:'btn btn-primary mx-3' %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<%= render 'form' %>

<%= link_to @pet.name, pet_path(@pet) %>

app/views/pets/index.html.erb
<h1>Here are our found pets</h1>

<ul>
  <% @pets.each do |pet|  %>
    <div>
      <li> <%= link_to pet.name, pet_path(pet) %> found: <%= pet.found_days_ago %></li>
    </div>
  <% end %>
</ul>

<%= link_to 'Add a new pet', new_pet_path %>

app/views/pets/new.html.erb
<%= render 'form' %>

<%= link_to 'Back to our amazing pet', pets_path %>

app/views/pets/show.html.erb
<div>
  <h1><%= @pet.name %> the <%= @pet.species %></h1>

  <h3>found: <%= @pet.found_days_ago %></h3>

  <p>Found at: <%= @pet.address %></p>
</div>

<div>
  <p><%= link_to 'Back to our amazing pets', pets_path %></p>
  <p><%= link_to "Change information about #{@pet.name}", edit_pet_path(@pet) %></p>
  <p><%= link_to 'Remove pet from database', delete_pet_path(@pet), method: 'delete', data: { confirm: "Are you sure?" } %></p>

</div>